### ISSUE TITLE
[BUG] fails with @asyncapi/parser-js 3.0.14

### ISSUE THREAD

**Issue by KhudaDad414** [smoya/asyncapi-adoption-metrics#30]
### Describe the bug.

After updating @asyncapi/parser-js to 3.0.14 I am getting the following error:
```bash
> @asyncapi/cli@1.8.4 pretest
> npm run build


> @asyncapi/cli@1.8.4 build
> rimraf lib && node scripts/fetch-asyncapi-example.js && tsc && oclif manifest && echo "Build Completed"

Fetched ZIP file
Unzipped all examples from zip
src/base.ts:46:43 - error TS2345: Argument of type 'AsyncAPIDocumentInterface' is not assignable to parameter of type 'AsyncAPIDocument'.
  Type 'import("upgrade-optimizer/node_modules/@asyncapi/parser/esm/models/asyncapi").AsyncAPIDocumentInterface' is not assignable to type 'import("upgrade-optimizer/node_modules/parserapiv3/esm/models/asyncapi").AsyncAPIDocumentInterface'.
    The types returned by 'info().contact()' are incompatible between these types.
      Type 'import("upgrade-optimizer/node_modules/@asyncapi/parser/esm/models/contact").ContactInterface | undefined' is not assignable to type 'import("upgrade-optimizer/node_modules/parserapiv3/esm/models/contact").ContactInterface | undefined'.
        Type 'import("upgrade-optimizer/node_modules/@asyncapi/parser/esm/models/contact").ContactInterface' is not assignable to type 'import("upgrade-optimizer/node_modules/parserapiv3/esm/models/contact").ContactInterface'.
          Property '_json' is protected but type 'BaseModel<J, M>' is not a class derived from 'BaseModel<J, M>'.

46           metadata = MetadataFromDocument(document, metadata);
                                             ~~~~~~~~

```

### Expected behavior

It should run without any errors.

### Screenshots

...

### How to Reproduce

1. update @asyncapi/parser-js in @asyncapi/cli to 3.0.14
2. run `npm install`
3. run `npm run test`

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by smoya** [comment]
The issue comes with an outdate parser version in the `@smoya/multi-parser` repo. Update comes here https://github.com/smoya/multi-parser-js/pull/15

More details about why this is not an automated process plus the work that is being done to fix it available in https://github.com/asyncapi/parser-js/issues/963

**Comment by smoya** [comment]
@KhudaDad414 Here is the PR updating to the recently released version of the `@smoya/multi-parser` package: https://github.com/smoya/asyncapi-adoption-metrics/pull/31

Merged ATM.
